# Generated by Django 5.2.3 on 2025-08-08 21:02

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]

