# Generated by Django 5.2.3 on 2025-07-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_transaction_id_order_transaction_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='orders.cartitem'),
        ),
    ]
